title: Hello, world! I'm David Ramirez
description: > # this means to ignore newlines until "baseurl:"
  I'm a market research consultant, graduate from the University of Wisconsin-Madison.
permalink: ':title/'
baseurl: "/deramirez1.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: David Ramirez # add your name
author-img: the-little-one-cover.jpg # add your photo
about-author: I am a data enthusiast, market researcher, and dog dad # add description
social-twitter: dave_e_ramirez # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: deramirez1 # add your Github handle
social-linkedin: davideramirez # add your Linkedin handle
social-email: deramirez1@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num/"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
